// <auto-generated />
using System;
using GestionCourrier.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionCirculationWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514100524_AddCabinetToEntiteDJ")]
    partial class AddCabinetToEntiteDJ
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionCourrier.Models.Entite", b =>
                {
                    b.Property<int>("IdEntite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEntite"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destinataire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstArchive")
                        .HasColumnType("bit");

                    b.Property<bool>("EstTransmissible")
                        .HasColumnType("bit");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtatWorkflow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdBureauOrdre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdService")
                        .HasColumnType("int");

                    b.Property<string>("LienPdf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDeCourrier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCorrespondance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeGenerale")
                        .HasColumnType("int");

                    b.Property<string>("TypeRegistre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEntite");

                    b.HasIndex("IdService");

                    b.ToTable("Entites");
                });

            modelBuilder.Entity("GestionCourrier.Models.EntiteDJ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cabinet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateArchivage")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destinataire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emplacement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntiteAdministratifId")
                        .HasColumnType("int");

                    b.Property<bool>("EstArchive")
                        .HasColumnType("bit");

                    b.Property<bool>("EstTransmissible")
                        .HasColumnType("bit");

                    b.Property<string>("EtatArchive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtatWorkflow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdBureauOrdre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdService")
                        .HasColumnType("int");

                    b.Property<string>("LienPdf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TribunalSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntiteAdministratifId");

                    b.HasIndex("IdService");

                    b.ToTable("EntitesDJs");
                });

            modelBuilder.Entity("GestionCourrier.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateDechargement")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstCharge")
                        .HasColumnType("bit");

                    b.Property<int>("Etat")
                        .HasColumnType("int");

                    b.Property<int>("IdService")
                        .HasColumnType("int");

                    b.Property<int>("Serial")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdService");

                    b.ToTable("Equipements");
                });

            modelBuilder.Entity("GestionCourrier.Models.Id", b =>
                {
                    b.Property<int>("IdBureauOrdre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBureauOrdre"));

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.HasKey("IdBureauOrdre");

                    b.ToTable("Ids");
                });

            modelBuilder.Entity("GestionCourrier.Models.NumeroDossierJuridique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<int>("EntiteDJId")
                        .HasColumnType("int");

                    b.Property<int>("Nombre")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSujet")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntiteDJId")
                        .IsUnique();

                    b.ToTable("NumerosDossierJuridique");
                });

            modelBuilder.Entity("GestionCourrier.Models.Registre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdService")
                        .HasColumnType("int");

                    b.Property<int>("TypeDeRegistre")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdService");

                    b.ToTable("Registres");
                });

            modelBuilder.Entity("GestionCourrier.Models.Reponse", b =>
                {
                    b.Property<int>("IdReponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReponse"));

                    b.Property<DateTime>("DateReponse")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegistreId")
                        .HasColumnType("int");

                    b.Property<int>("Resultat")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReponse");

                    b.HasIndex("RegistreId");

                    b.ToTable("Reponses");
                });

            modelBuilder.Entity("GestionCourrier.Models.Retrait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateDeRetour")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDeRetrait")
                        .HasColumnType("datetime2");

                    b.Property<string>("EffectuePar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntiteDJId")
                        .HasColumnType("int");

                    b.Property<string>("MotifDeRetrait")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntiteDJId");

                    b.ToTable("Retraits");
                });

            modelBuilder.Entity("GestionCourrier.Models.Service", b =>
                {
                    b.Property<int>("IdService")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdService");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("GestionCourrier.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcceptedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("AcceptedByUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReponse")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationUserId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentSujet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DoitRevenir")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageReponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationServiceId");

                    b.HasIndex("DestinationUserId");

                    b.HasIndex("SourceServiceId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("GestionCourrier.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdService")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubstituteUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdService");

                    b.HasIndex("SubstituteUserId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("GestionCourrier.Models.Entite", b =>
                {
                    b.HasOne("GestionCourrier.Models.Service", "Service")
                        .WithMany("Entites")
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GestionCourrier.Models.EntiteDJ", b =>
                {
                    b.HasOne("GestionCourrier.Models.Entite", "EntiteAdministratif")
                        .WithMany()
                        .HasForeignKey("EntiteAdministratifId");

                    b.HasOne("GestionCourrier.Models.Service", "Service")
                        .WithMany("EntitesDJ")
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntiteAdministratif");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GestionCourrier.Models.Equipment", b =>
                {
                    b.HasOne("GestionCourrier.Models.Service", "Service")
                        .WithMany("Equipements")
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GestionCourrier.Models.NumeroDossierJuridique", b =>
                {
                    b.HasOne("GestionCourrier.Models.EntiteDJ", "EntiteDJ")
                        .WithOne("NumeroDossier")
                        .HasForeignKey("GestionCourrier.Models.NumeroDossierJuridique", "EntiteDJId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntiteDJ");
                });

            modelBuilder.Entity("GestionCourrier.Models.Registre", b =>
                {
                    b.HasOne("GestionCourrier.Models.Service", "Service")
                        .WithMany("Registres")
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GestionCourrier.Models.Reponse", b =>
                {
                    b.HasOne("GestionCourrier.Models.Registre", "Registre")
                        .WithMany("Reponses")
                        .HasForeignKey("RegistreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registre");
                });

            modelBuilder.Entity("GestionCourrier.Models.Retrait", b =>
                {
                    b.HasOne("GestionCourrier.Models.EntiteDJ", "EntiteDJ")
                        .WithMany("Retraits")
                        .HasForeignKey("EntiteDJId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntiteDJ");
                });

            modelBuilder.Entity("GestionCourrier.Models.Transaction", b =>
                {
                    b.HasOne("GestionCourrier.Models.Service", "DestinationService")
                        .WithMany()
                        .HasForeignKey("DestinationServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionCourrier.Models.Utilisateur", "DestinationUser")
                        .WithMany()
                        .HasForeignKey("DestinationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GestionCourrier.Models.Service", "SourceService")
                        .WithMany()
                        .HasForeignKey("SourceServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinationService");

                    b.Navigation("DestinationUser");

                    b.Navigation("SourceService");
                });

            modelBuilder.Entity("GestionCourrier.Models.Utilisateur", b =>
                {
                    b.HasOne("GestionCourrier.Models.Service", "Service")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("IdService")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionCourrier.Models.Utilisateur", "SubstituteUser")
                        .WithMany()
                        .HasForeignKey("SubstituteUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Service");

                    b.Navigation("SubstituteUser");
                });

            modelBuilder.Entity("GestionCourrier.Models.EntiteDJ", b =>
                {
                    b.Navigation("NumeroDossier");

                    b.Navigation("Retraits");
                });

            modelBuilder.Entity("GestionCourrier.Models.Registre", b =>
                {
                    b.Navigation("Reponses");
                });

            modelBuilder.Entity("GestionCourrier.Models.Service", b =>
                {
                    b.Navigation("Entites");

                    b.Navigation("EntitesDJ");

                    b.Navigation("Equipements");

                    b.Navigation("Registres");

                    b.Navigation("Utilisateurs");
                });
#pragma warning restore 612, 618
        }
    }
}
